---

- id: standard
  name: JavaScript Standard Style
  entry: standard
  language: system
  types: [javascript]

- id: snyk-test
  name: Test for known vulnerabilities using Snyk
  entry: snyk
  args: [
    "test"
  ]
  language: system
